###################### Filebeat Configuration Example #########################



filebeat.inputs:

  - type: filestream

    # Unique ID among all inputs, an ID is required.
    id: {{ component }}

    # Change to true to enable this input configuration.
    enabled: true

    # Paths that should be crawled and fetched. Glob based paths.
    paths:
      - {{ log_path }}
      #- c:\programdata\elasticsearch\logs\*

  # ------------------------------ Logstash Output -------------------------------
  output.logstash:
  # The Logstash hosts
  hosts: ["172.31.31.83:5044"]

# ============================== Filebeat modules ==============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

  # Period on which files under path should be checked for changes
  #reload.period: 10s

# ======================= Elasticsearch template setting =======================

setup.template.settings:
  index.number_of_shards: 1



# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

