- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed
- name: Copy roboshop Config file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
- name: Clean Old App content
  ansible.builtin.shell:
    cmd: rm -rf /usr/share/nginx/html/*
- name: Download App Content
  ansible.builtin.uri:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /tmp/frontend.zip
- name: Extracting App Content
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
- name: Start Nginx
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: nginx


