- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed
- name: Copy roboshop Config file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
- name: Clean Old App content
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent
- name: Create App Dir
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory
- name: download and Extracting App Content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes
- name: Start Nginx
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: nginx

- name: install file beat
  ansible.builtin.inport_role:
    name: elk
    tasks_from: filebeat



