- name: import file beat repo file
  ansible.builtin.templates:
    src: elk.repo
    dest: /etc/yum.repos.yum

- name: install file beat
  ansible.builtin.yum:
    name: filebeat
    state: installed

- name: copy file beat config file
  ansible.builtin.templates:
    src: filebeat.repo
    dest: /etc/filebeat/filebeat.yml

- name: systemd reload
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: true
