- name: import elastic  repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/filebeat.repo

- name: install file beat
  ansible.builtin.yum:
    name: filebeat
    state: installed

- name: copy file beat config file
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: systemd reload
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: true
