- name: setup catalogue
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: install prometheus node exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter