labels:
  - { tag: Name, label: name }
  - { tag: env, label: env }

components:
  - {name: cart, service_name= cart}
  - {name: catalogue, service_name= catalogue}
  - {name: shipping, service_name= shipping}
  - {name: payment, service_name= payment}
  - {name: user, service_name= user}
  - {name: frontend, service_name= nginx}

