
- name: copy mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d
- name: install mongo schema
  ansible.builtin.shell: yum install mongodb-org-shell -y

- name: load schema
  ansible.builtin.shell: mongo --host {{ lookup( 'aws_ssm', 'dev.mongo_url', region='us_east_1' ) }} </app/schema/catalogue.js