- name: Install Python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: add user
  ansible.builtin.import_tasks:
    file: check_user.yml

- name: get app content
  ansible.builtin.import_tasks:
    file: get_app_content.yml

- name: install python dependancies and update passowrd
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: get app content
  ansible.builtin.import_tasks:
    file: systemd.yml

