- name: Setup SystemD Service
  ansible.builtin.template:
    src: "{{component}}.service"
    dst: /etc/systemd/system/{{component}}.service
- name: Start service
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: "{{ component }}"