- name: Setup SystemD Service
  ansible.builtin.copy:
    src: "{{component}}.service"
    dst: /etc/systemd/system
- name: Start service
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: "{{ component }}"